name: '${name}'
version: '${version}'
main: '${main}'

commands:
  togglepvp:
    description: Toggle PVP
    aliases:
      - tpvp
      - pvp
    permission: togglepvp.command.togglepvp
  setpvp:
    description: Set PVP
    aliases:
      - spvp
      - pvpset
    permission: togglepvp.command.setpvp