name: '${name}'
version: '${version}'
main: '${main}'

commands:
  togglepvp:
    description: Toggle PVP
    aliases:
      - tpvp
      - pvp
    permission: pacifism.command.togglepvp
  setpvp:
    description: Set PVP
    aliases:
      - spvp
      - pvpset
    permission: pacifism.command.setpvp
  worldwhitelist:
    description: World Whitelist
    aliases:
      - wwl
      - whitelist
    permission: pacifism.command.worldwhitelist