name: '${name}'
version: '${version}'
main: '${main}'
folia-supported: true
authors: [ Drak ]
depend:
  - BukkitOfUtils
softdepend:
  - PlaceholderAPI

commands:
  togglepvp:
    description: Toggle PVP
    aliases:
      - tpvp
      - pvp
    permission: pacifism.command.togglepvp
  setpvp:
    description: Set PVP
    aliases:
      - spvp
      - pvpset
    permission: pacifism.command.setpvp
  worldwhitelist:
    description: World Whitelist
    aliases:
      - wwl
    permission: pacifism.command.worldwhitelist
  setgracetime:
    description: Set Grace Time
    aliases:
      - sgt
      - gtset
    permission: pacifism.command.setgracetime